version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: retail_oltp_db
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_pass
      POSTGRES_DB: retail_oltp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retail_user -d retail_oltp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: